import type { Metadata } from 'next';

import '@/app/globals.css';

import localFont from 'next/font/local';

import RootClientLayout from '@/components/layout/RootClientLayout';
import { TransitionsProvider } from '@/providers/TransitionProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: '../static/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={pretendard.variable}>
      <TransitionsProvider>
        <RootClientLayout>{children}</RootClientLayout>
      </TransitionsProvider>
    </html>
  );
}
